### ISSUE TITLE
missing html elements in the idl

### ISSUE THREAD

**Issue by jjl** [stefan-hoeck/idris2-webidl#33]
for example, 'section'. you note that you extracted it from [here](https://html.spec.whatwg.org/multipage/indices.html), which contains section (at least now). was this an automated extraction you just need to regenerate or should i consider trying to merge in the missing information?

**Comment by stefan-hoeck** [comment]
I'm not sure what this is about. The link you posted does not contain any WebIDL specifications. To the best of my knowledge, there is no WebIDL interface corresponding to `<section>`. According to your link, the interface for `<section>` is `HTMLElement`. Could you please elaborate on this?

**Comment by stefan-hoeck** [comment]
Ah, my bad: The link in the `html.webidl` file points to the multipage version (which is the link you used above). Still I'm confused about what's missing with regard to `<section>` elements.

**Comment by stefan-hoeck** [comment]
But as I wrote above, there is no WebIDL interface corresponding to a select element, so I'm still not sure what you expect to be in `html.webidl` that is currently missing. And no, the `.webidl` files were not generated or extracted automatically: They were assembled manually from the different specs.

**Comment by stefan-hoeck** [comment]
> i want to use elements that are missing from the 'dom' library (right now, 'section' and 'figure', but i'm sure i'll find others and various attributes), and i assume the way to go about that is to edit the IDL files.
> 
> should i go collate the missing information and PR them into the IDLs or would you recommend a different approach?

Could you please point me to where these elements are missing in the DOM library? `<section>` and `<figure>` are element tags without their own WebIDL interfaces: The link you posted above will show you that the WebIDL interface for `<section>` and `<figure>` is `HTMLElement` in both cases. Therefore, these are not missing from the WebIDL specs, because the corresponding WebIDL interface is already there.

Therefore, if you think these elements should appear somewhere in the idris2-dom library, I'm quite sure that they would have to be added to one of the manually written modules such as `Web.Dom` or `Web.Html`.

**Comment by stefan-hoeck** [comment]
Thanks and feel free to open an issue or PR at idris2-dom.
